"""
app.py — Streamlit GUI for the Books RAG assistant.

Run from the project root:
    streamlit run app.py

The interface exposes the full pipeline so it's easy to test and demo:
  - question input + submit button
  - final generated answer
  - original query, rewritten query, query class, extracted filters
  - retrieved source chunks with similarity scores and metadata
  - a dense/hybrid retrieval toggle (Level 3)

Per the brief, this GUI code is the one part allowed to be AI-generated;
it calls the hand-written pipeline in src/.
"""

import sys
from pathlib import Path

import streamlit as st

# make src/ importable
sys.path.insert(0, str(Path(__file__).resolve().parent / "src"))
from pipeline import answer_question  # noqa: E402

st.set_page_config(page_title="Books RAG Assistant", page_icon="📚", layout="wide")

# ---- header --------------------------------------------------------------
st.title("📚 Books RAG Assistant")
st.caption(
    "Ask a natural-language question about the book catalogue. "
    "Answers are grounded in retrieved catalogue data and generated by Gemini."
)

# ---- controls ------------------------------------------------------------
with st.sidebar:
    st.header("Settings")
    retrieval_mode = st.radio(
        "Retrieval method",
        options=["Hybrid (dense + BM25)", "Dense only"],
        help="Hybrid fuses semantic and keyword search (Level 3). "
             "Dense is embeddings-only (Level 1).",
    )
    use_hybrid = retrieval_mode.startswith("Hybrid")
    use_qi = st.checkbox(
        "Query intelligence (rewrite / classify / filter)",
        value=True,
        help="Level 2: rewrite the query, classify it, and extract filters "
             "before retrieval.",
    )
    top_k = st.slider("Number of chunks to retrieve (k)", 1, 10, 5)

# ---- input ---------------------------------------------------------------
query = st.text_input(
    "Your question",
    placeholder="e.g. highly rated history books under £40",
)
ask = st.button("Ask", type="primary")

# ---- run -----------------------------------------------------------------
if ask and query.strip():
    with st.spinner("Retrieving and generating..."):
        result = answer_question(
            query.strip(),
            k=top_k,
            use_query_intelligence=use_qi,
            use_hybrid=use_hybrid,
        )

    # ---- answer ----------------------------------------------------------
    st.subheader("Answer")
    st.write(result["answer"])

    # ---- query understanding --------------------------------------------
    if use_qi:
        st.subheader("Query understanding")
        c1, c2 = st.columns(2)
        with c1:
            st.markdown("**Original query**")
            st.info(result["query"])
            st.markdown("**Query class**")
            st.info(result.get("query_class") or "—")
        with c2:
            st.markdown("**Rewritten query**")
            st.info(result["rewritten_query"])
            st.markdown("**Extracted filters**")
            st.json(result["filters"] if result["filters"] else {})

    # ---- sources ---------------------------------------------------------
    st.subheader(f"Retrieved sources · {result.get('retrieval_mode', '')} retrieval")
    if not result["chunks"]:
        st.warning("No sources retrieved for this query.")
    for c in result["chunks"]:
        m = c["metadata"]
        header = f"[{c['rank']}] {m['title']}  ·  score {c['score']:.3f}"
        with st.expander(header):
            meta_cols = st.columns(4)
            meta_cols[0].metric("Price", f"£{m['price']:.2f}")
            meta_cols[1].metric("Rating", f"{m['rating']}/5")
            meta_cols[2].metric("Category", m["category"])
            meta_cols[3].metric("In stock", "Yes" if m.get("in_stock") else "No")
            st.markdown("**Chunk text**")
            st.text(c["text"])
            if m.get("source_url"):
                st.markdown(f"[View on source site]({m['source_url']})")

elif ask:
    st.warning("Please type a question first.")
